# This is the default configuration settings which will be loaded in the first place.
# If you rename or want to use another file, update also the name in docker-compose file.
# All settings defined here will be overrided by the content of `app.env` file. You can 
# update the content of `app.env` per your need (dev or staging or prod). If you rename
# this file, you must update the naming used in the `docker-compose.yml` file as well.

# False for developement mode and
# logs is printed on console and file
is_production: false
log_level: "info"
log_file: "logs/logs.log"

# Could be manually set or envs variables
# or auto detected with build flags.
git_commit: ""
git_tag: ""
build_time: ""

# Determines the injection of ops endpoints.
ops_endpoints_enable: true

# Determines the injection of http-based
# pprof endpoints on the server. If `True`
# ensure `ops_endpoints_enable` is enabled.
profiler_endpoints_enable: true

# Api server settings
server:
  host: "0.0.0.0"
  port: "8080"
  read_timeout: 5s
  write_timeout: 17s
  request_timeout: 15s
  shutdown_timeout: 90s
  certs_file: "./server.crt"
  key_file: "./server.key"

# Redis settings
redis:
  host: "db.demo.redis"
  port: "6379"
  dial_timeout: 30s
  read_timeout: 30s
  pool_size: 10
  pool_timeout: 30s
  username: ""
  password: "<secret>"
  db_index: 1

# BoltDB settings
boltdb:
  filepath: "./db.demo.bolt"
  bucket_name: "books"
  timeout: 5s
